import type { Metadata } from "next";
import {Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import MarqueeScroll from "@/components/MarqueeScroll";
import { Toaster } from "react-hot-toast";

const notoSerifBengali = Noto_Serif_Bengali({
  
  subsets: ["latin", "bengali"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme='light'
      className={`${notoSerifBengali.className} h-full antialiased scroll-smooth`}
    >
      <body className="bg-[#f0f5f0] min-h-full flex flex-col">
        <Header/>
        <MarqueeScroll/>
        <main className=" w-full max-w-7xl mx-auto">{children}</main>
        <Toaster/>
      </body>
    </html>
  );
}
